backend:
  name: git-gateway
  branch: main

site_url: https://strahova.biz.ua
logo_url: https://strahova.biz.ua/images/logo.png

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "pages"
    label: "Сторінки"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Назва", name: "title", widget: "string" }
      - { label: "Тіло", name: "body", widget: "markdown" }

  - name: "posts"
    label: "Новини"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Назва", name: "title", widget: "string" }
      - { label: "Дата", name: "date", widget: "datetime" }
      - { label: "Контент", name: "body", widget: "markdown" }
