backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

site_url: https://strahova.biz.ua
display_url: https://strahova.biz.ua

collections:
  - name: "pages"
    label: "Сторінки"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Назва сторінки", name: "title", widget: "string" }
      - { label: "Основний текст", name: "body", widget: "markdown" }

