backend:
  name: github
  repo: karpatytk/strahova.biz.ua
  branch: main

media_folder: "images"
public_folder: "/images"

site_url: https://strahova.biz.ua

collections:
  - name: "pages"
    label: "Сторінки"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Назва", name: "title", widget: "string" }
      - { label: "Тіло сторінки", name: "body", widget: "markdown" }
