backend:
  name: github
  repo: karpatytk/strahova.biz.ua
  branch: main
  base_url: https://strahova.biz.ua
  auth_endpoint: api/auth
  site_domain: strahova.biz.ua

site_url: https://strahova.biz.ua
logo_url: https://strahova.biz.ua/images/logo.png

media_folder: "images" # де зберігаються зображення
public_folder: "/images"

collections:
  - name: "pages"
    label: "Сторінки"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Назва", name: "title", widget: "string" }
      - { label: "Контент", name: "body", widget: "markdown" }

  - name: "posts"
    label: "Новини"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Назва", name: "title", widget: "string" }
      - { label: "Дата", name: "date", widget: "datetime" }
      - { label: "Контент", name: "body", widget: "markdown" }
